MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = lite

RGBLIGHT_ENABLE = yes
VELOCIKEY_ENABLE = yes
OLED_DRIVER_ENABLE = yes
WPM_ENABLE = yes

ENCODER_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
