/* Copyright 2019 Thomas Baart <thomas@splitkb.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#include QMK_KEYBOARD_H
#include "features/casemodes.h"

#ifdef CONSOLE_ENABLE
#include "print.h"
#endif

enum layers {
    _QWERTY = 0,
    _NAV,
    _NUM,
    _FN,
    _GAME,
};

enum custom_keycodes {
    ARROW = SAFE_RANGE,
    LOWER,
    GREATER,
    DELAY,
    CMD_TAB,
    ALT_TAB,
    CAPSWORD,
    XCASE
};

/*
* HRM
*/
#define HRM_A LCTL_T(KC_A)
#define HRM_S LALT_T(KC_S)
#define HRM_D LGUI_T(KC_D)
#define HRM_F LSFT_T(KC_F)
#define HRM_J RSFT_T(KC_J)
#define HRM_K RGUI_T(KC_K)
#define HRM_L RALT_T(KC_L)
#define HRM_COL LCTL_T(KC_SCLN)

/*
* Layers and shift
*/
#define NAV_BSPC LT(_NAV, KC_BSPC)
#define FN_DEL LT(_FN, KC_DELETE)
#define NUM_ENT LT(_NUM, KC_ENT)
#define NAV_SPC LT(_NAV, KC_SPC)
#define OSM_SFT OSM(MOD_LSFT)
#define GAME TT(_GAME)

/*
* OSX symbols shortcuts
*/
#define EURO RALT(LSFT(KC_2))
#define POUND RALT(KC_3)
#define OCQUOTE RALT(KC_RBRC)
#define ODCQUOTE RALT(KC_LBRC)
#define CCQUOTE RALT(LSFT(KC_RBRC))
#define CDCQUOTE RALT(LSFT(KC_LBRC))

/*
* OSX action shortcuts
*/

#define UNDO LGUI(KC_Z)
#define CUT LGUI(KC_X)
#define COPY LGUI(KC_C)
#define PASTE LGUI(KC_V)

#define FORCEQ LALT(LGUI(KC_ESCAPE))
#define LOCKSCR LCTL(LGUI(KC_Q))

#define PRTSCR1 LCTL(LGUI(LSFT(KC_3)))
#define PRTSCR2 LCTL(LGUI(LSFT(KC_4)))
#define PRTSCR3 LGUI(LSFT(KC_5))

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ,-----------------------------------------.                              ,-----------------------------------------.
 * | TAB  |  Q   |  W   |  E   |  R   |  T   |                              |  Y   |  U   |  I   |  O   |  P   | BSLS |
 * |------+------+------+------+------+------|                              |------+------+------+------+------+------|
 * | GRV  |HRM_A |HRM_S |HRM_D |HRM_F |  G   |                              |  H   |HRM_J |HRM_K |HRM_L |HRM_CO| QUOT |
 * |------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------|
 * | LSPO |  Z   |  X   |  C   |  V   |  B   |      |      |  |      |      |  N   |  M   | COMM | DOT  | SLSH | RSPC |
 * `------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------'
 *                      | MPLY |ALT_TA|CMD_TA|NAV_BS|FN_DEL|  |NUM_EN|NAV_SP|OSM_SF|      | MUTE |
 *                      |      |      |      |      |      |  |      |      |      |      |      |
 *                      `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
    [_QWERTY] = LAYOUT(
     KC_TAB,    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                                           KC_Y,    KC_U,    KC_I,    KC_O,    KC_P, KC_BSLS,
     KC_GRV,   HRM_A,   HRM_S,   HRM_D,   HRM_F,    KC_G,                                           KC_H,   HRM_J,   HRM_K,   HRM_L, HRM_COL, KC_QUOT,
    KC_LSPO,    KC_Z,    KC_X,    KC_C,    KC_V,    KC_B, XXXXXXX, XXXXXXX,    XXXXXXX, XXXXXXX,    KC_N,    KC_M, KC_COMM,  KC_DOT, KC_SLSH, KC_RSPC,
                               KC_MPLY, ALT_TAB, CMD_TAB,NAV_BSPC,  FN_DEL,    NUM_ENT, NAV_SPC, OSM_SFT, XXXXXXX, KC_MUTE
    ),
/* ,-----------------------------------------.                              ,-----------------------------------------.
 * | TAB  | CIRC |  AT  | HASH | AMPR |      |                              | PGUP | HOME |  UP  | END  |      | PERC |
 * |------+------+------+------+------+------|                              |------+------+------+------+------+------|
 * | ESC  | LCTL | LALT | LGUI | LSFT | MINS |                              | PGDN | LEFT | DOWN | RGHT |ARROW | CAPS |
 * |------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------|
 * | LSPO | UNDO | CUT  | COPY |PASTE | UNDS |      |      |  |      |      |      |      |LOWER |GREATE| EXLM | RSPC |
 * `------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------'
 *                      |      |ALT_TA|CMD_TA| BSPC | DEL  |  | ENT  | SPC  |      |      |      |
 *                      |      |      |      |      |      |  |      |      |      |      |      |
 *                      `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
    [_NAV] = LAYOUT(
     KC_TAB, KC_CIRC,   KC_AT, KC_HASH, KC_AMPR, XXXXXXX,                                        KC_PGUP, KC_HOME,   KC_UP,  KC_END, XXXXXXX, KC_PERC,
     KC_ESC, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_MINS,                                        KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT,   ARROW, KC_CAPS,
    KC_LSPO,    UNDO,     CUT,    COPY,   PASTE, KC_UNDS, XXXXXXX, XXXXXXX,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,   LOWER, GREATER, KC_EXLM, KC_RSPC,
                               XXXXXXX, ALT_TAB, CMD_TAB, KC_BSPC,  KC_DEL,     KC_ENT,  KC_SPC, XXXXXXX, XXXXXXX, XXXXXXX
    ),
/* ,-----------------------------------------.                              ,-----------------------------------------.
 * | TAB  |OCQUOT|CCQUOT| LCBR | RCBR | DLR  |                              | MINS |  7   |  8   |  9   | SLSH | PERC |
 * |------+------+------+------+------+------|                              |------+------+------+------+------+------|
 * | ESC  | LCTL | LALT | LGUI | LSFT | EURO |                              | PLUS |  4   |  5   |  6   | ASTR | CAPS |
 * |------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------|
 * | LSPO |ODCQUO|CDCQUO| LBRC | RBRC |POUND |      |      |  |      |      |  0   |  1   |  2   |  3   | EQL  | RSPC |
 * `------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------'
 *                      |      |      |      | BSPC | DEL  |  | ENT  | SPC  | DOT  | COMM |      |
 *                      |      |      |      |      |      |  |      |      |      |      |      |
 *                      `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
    [_NUM] = LAYOUT(
     KC_TAB, OCQUOTE, CCQUOTE, KC_LCBR, KC_RCBR,  KC_DLR,                                        KC_MINS,    KC_7,    KC_8,    KC_9, KC_SLSH, KC_PERC,
     KC_ESC, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT,    EURO,                                        KC_PLUS,    KC_4,    KC_5,    KC_6, KC_ASTR, KC_CAPS,
    KC_LSPO,ODCQUOTE, CDCQUOTE,KC_LBRC, KC_RBRC,   POUND,  XXXXXXX, XXXXXXX,    XXXXXXX, XXXXXXX,   KC_0,    KC_1,    KC_2,    KC_3,  KC_EQL, KC_RSPC,
                               XXXXXXX, XXXXXXX, XXXXXXX,  KC_BSPC,  KC_DEL,     KC_ENT,  KC_SPC, KC_DOT, KC_COMM, XXXXXXX
    ),
/* ,-----------------------------------------.                              ,-----------------------------------------.
 * |LOCKSC|      |      |DM_REC|DM_PLY|RGB_VA|                              |RGB_VA|  F7  |  F8  |  F9  | F10  |PRTSCR|
 * |------+------+------+------+------+------|                              |------+------+------+------+------+------|
 * |FORCEQ| LCTL | LALT | LGUI | LSFT |RGB_HU|                              |RGB_HU|  F4  |  F5  |  F6  | F11  |PRTSCR|
 * |------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------|
 * |DELAY |      |      |DM_REC|DM_PLY|RGB_RM|      |      |  |      |      |RGB_MO|  F1  |  F2  |  F3  | F12  |PRTSCR|
 * `------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------'
 *                      |      |      |RGB_TO|      |      |  |      |XCASE |CAPSWO| GAME |      |
 *                      |      |      |      |      |      |  |      |      |      |      |      |
 *                      `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
    [_FN] = LAYOUT(
    LOCKSCR, XXXXXXX, XXXXXXX, DM_REC1, DM_PLY1, RGB_VAD,                                        RGB_VAI,   KC_F7,   KC_F8,   KC_F9,  KC_F10, PRTSCR1,
     FORCEQ, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, RGB_HUD,                                        RGB_HUI,   KC_F4,   KC_F5,   KC_F6,  KC_F11, PRTSCR2,
      DELAY, XXXXXXX, XXXXXXX, DM_REC2, DM_PLY2,RGB_RMOD,  XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX,  RGB_MOD,   KC_F1,   KC_F2,   KC_F3,  KC_F12, PRTSCR3,
                               XXXXXXX, XXXXXXX, RGB_TOG,  XXXXXXX, XXXXXXX,  XXXXXXX,   XCASE, CAPSWORD,    GAME, XXXXXXX
    ),
/* ,-----------------------------------------.                              ,-----------------------------------------.
 * |      | TAB  |  Q   |  W   |  E   |  R   |                              |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                              |------+------+------+------+------+------|
 * |      | ESC  |  A   |  S   |  D   |  F   |                              |      |      |      |      |      |      |
 * |------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------|
 * |      | LSFT |  Z   |  X   |  C   |  V   |      |      |  |      |      |      |      |      |      |      |      |
 * `------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------'
 *                      |      |      |      | SPC  | BSPC |  |      |      |      | GAME |      |
 *                      |      |      |      |      |      |  |      |      |      |      |      |
 *                      `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
    [_GAME] = LAYOUT(
    XXXXXXX,  KC_TAB,    KC_Q,    KC_W,    KC_E,    KC_R,                                         XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX,  KC_ESC,    KC_A,    KC_S,    KC_D,    KC_F,                                         XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, KC_LSFT,    KC_Z,    KC_X,    KC_C,    KC_V,  XXXXXXX, XXXXXXX,    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                               XXXXXXX, XXXXXXX, XXXXXXX,   KC_SPC, KC_BSPC,    XXXXXXX, XXXXXXX, XXXXXXX,    GAME, XXXXXXX
    ),
};

bool use_default_xcase_separator(uint16_t keycode, const keyrecord_t *record) {
    switch (keycode) {
        case KC_A ... KC_Z:
        case KC_1 ... KC_0:
            return true;
    }
    return false;
}

bool get_tapping_force_hold(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case NAV_BSPC:
        case FN_DEL:
        case NUM_ENT:
        case NAV_SPC:
        case HRM_S:
        case HRM_L:
            return true;
        default:
            return false;
    }
}

bool is_cmd_tab_active = false;
bool is_alt_tab_active = false;
uint16_t cmd_tab_timer = 0;
uint16_t alt_tab_timer = 0;

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    #ifdef CONSOLE_ENABLE
        if (record->event.pressed) {
            uprintf("0x%04X,%u,%u,%u,%b,0x%02X,0x%02X,%u\n",
                keycode,
                record->event.key.row,
                record->event.key.col,
                get_highest_layer(layer_state),
                record->event.pressed,
                get_mods(),
                get_oneshot_mods(),
                record->tap.count
            );
        }
    #endif

    switch (keycode) {
        case ARROW:
            if (record->event.pressed) {
                tap_code(KC_MINS);
                tap_code16(KC_GT);
            }
            return false;
        case LOWER:
            if (record->event.pressed) {
                tap_code16(KC_LT);
                tap_code(KC_EQL);
            }
            return false;
        case GREATER:
            if (record->event.pressed) {
                tap_code16(KC_GT);
                tap_code(KC_EQL);
            }
            return false;
        case DELAY:
            if (record->event.pressed) {
                _delay_ms(500);
            }
            return false;
        case CMD_TAB:
            if (record->event.pressed) {
                if (!is_cmd_tab_active) {
                    is_cmd_tab_active = true;
                    register_code(KC_LGUI);
                }
                cmd_tab_timer = timer_read();
                register_code(KC_TAB);
            } else {
                unregister_code(KC_TAB);
            }
            return false;
        case ALT_TAB:
            if (record->event.pressed) {
                if (!is_alt_tab_active) {
                    is_alt_tab_active = true;
                    register_code(KC_LALT);
                }
                alt_tab_timer = timer_read();
                register_code(KC_TAB);
            } else {
                unregister_code(KC_TAB);
            }
            return false;
        case CAPSWORD:
            if (record->event.pressed) {
                enable_caps_word();
            }
            return false;
        case XCASE:
            if (record->event.pressed) {
                enable_xcase();
            }
            return false;
    }

    if (!process_case_modes(keycode, record)) {
        return false;
    }

    return true;
};

void matrix_scan_user(void) {
    if (is_cmd_tab_active) {
        if (timer_elapsed(cmd_tab_timer) > 350 && get_highest_layer(layer_state) != _NAV) {
            unregister_code(KC_LGUI);
            is_cmd_tab_active = false;
        }
    }
    if (is_alt_tab_active) {
        if (timer_elapsed(alt_tab_timer) > 350 && get_highest_layer(layer_state) != _NAV) {
            unregister_code(KC_LALT);
            is_alt_tab_active = false;
        }
    }
}

#ifdef ENCODER_ENABLE
bool encoder_update_user(uint8_t index, bool clockwise) {
    switch (get_highest_layer(layer_state)) {
        case _QWERTY:
        case _GAME:
            if (index == 0) {
                clockwise ? tap_code(KC_MEDIA_NEXT_TRACK) : tap_code(KC_MEDIA_PREV_TRACK);
            } else {
                clockwise ? tap_code(KC_AUDIO_VOL_UP) : tap_code(KC_AUDIO_VOL_DOWN);
            }
            break;
        case _NAV:
        case _NUM:
            clockwise ? tap_code16(LSFT(LGUI(KC_Z))) : tap_code16(LGUI(KC_Z));
            break;
        case _FN:
            clockwise ? tap_code(KC_BRMU) : tap_code(KC_BRMD);
            break;
    }
    return true;
}
#endif

#ifdef OLED_ENABLE
oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_180;
}

static void render_kyria_logo(void) {
    static const char PROGMEM kyria_logo[] = {
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,128,128,192,224,240,112,120, 56, 60, 28, 30, 14, 14, 14,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7, 14, 14, 14, 30, 28, 60, 56,120,112,240,224,192,128,128,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,192,224,240,124, 62, 31, 15,  7,  3,  1,128,192,224,240,120, 56, 60, 28, 30, 14, 14,  7,  7,135,231,127, 31,255,255, 31,127,231,135,  7,  7, 14, 14, 30, 28, 60, 56,120,240,224,192,128,  1,  3,  7, 15, 31, 62,124,240,224,192,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,240,252,255, 31,  7,  1,  0,  0,192,240,252,254,255,247,243,177,176, 48, 48, 48, 48, 48, 48, 48,120,254,135,  1,  0,  0,255,255,  0,  0,  1,135,254,120, 48, 48, 48, 48, 48, 48, 48,176,177,243,247,255,254,252,240,192,  0,  0,  1,  7, 31,255,252,240,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,255,255,255,  0,  0,  0,  0,  0,254,255,255,  1,  1,  7, 30,120,225,129,131,131,134,134,140,140,152,152,177,183,254,248,224,255,255,224,248,254,183,177,152,152,140,140,134,134,131,131,129,225,120, 30,  7,  1,  1,255,255,254,  0,  0,  0,  0,  0,255,255,255,  0,  0,  0,  0,255,255,  0,  0,192,192, 48, 48,  0,  0,240,240,  0,  0,  0,  0,  0,  0,240,240,  0,  0,240,240,192,192, 48, 48, 48, 48,192,192,  0,  0, 48, 48,243,243,  0,  0,  0,  0,  0,  0, 48, 48, 48, 48, 48, 48,192,192,  0,  0,  0,  0,  0,
        0,  0,  0,255,255,255,  0,  0,  0,  0,  0,127,255,255,128,128,224,120, 30,135,129,193,193, 97, 97, 49, 49, 25, 25,141,237,127, 31,  7,255,255,  7, 31,127,237,141, 25, 25, 49, 49, 97, 97,193,193,129,135, 30,120,224,128,128,255,255,127,  0,  0,  0,  0,  0,255,255,255,  0,  0,  0,  0, 63, 63,  3,  3, 12, 12, 48, 48,  0,  0,  0,  0, 51, 51, 51, 51, 51, 51, 15, 15,  0,  0, 63, 63,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 48, 48, 63, 63, 48, 48,  0,  0, 12, 12, 51, 51, 51, 51, 51, 51, 63, 63,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 15, 63,255,248,224,128,  0,  0,  3, 15, 63,127,255,239,207,141, 13, 12, 12, 12, 12, 12, 12, 12, 30,127,225,128,  0,  0,255,255,  0,  0,128,225,127, 30, 12, 12, 12, 12, 12, 12, 12, 13,141,207,239,255,127, 63, 15,  3,  0,  0,128,224,248,255, 63, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  3,  7, 15, 62,124,248,240,224,192,128,  1,  3,  7, 15, 30, 28, 60, 56,120,112,112,224,224,225,231,254,248,255,255,248,254,231,225,224,224,112,112,120, 56, 60, 28, 30, 15,  7,  3,  1,128,192,224,240,248,124, 62, 15,  7,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  3,  7, 15, 14, 30, 28, 60, 56,120,112,112,112,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,112,112,112,120, 56, 60, 28, 30, 14, 15,  7,  3,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
    };
    oled_write_raw_P(kyria_logo, sizeof(kyria_logo));
}

static void render_qmk_logo(void) {
    static const char PROGMEM qmk_logo[] = {
        0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8a,0x8b,0x8c,0x8d,0x8e,0x8f,0x90,0x91,0x92,0x93,0x94,
        0xa0,0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7,0xa8,0xa9,0xaa,0xab,0xac,0xad,0xae,0xaf,0xb0,0xb1,0xb2,0xb3,0xb4,
        0xc0,0xc1,0xc2,0xc3,0xc4,0xc5,0xc6,0xc7,0xc8,0xc9,0xca,0xcb,0xcc,0xcd,0xce,0xcf,0xd0,0xd1,0xd2,0xd3,0xd4,0
    };
    oled_write_P(qmk_logo, false);
}

#ifdef DYNAMIC_MACRO_ENABLE
bool is_recording_dynamic_macro = false;

void dynamic_macro_record_start_user(void) {
    is_recording_dynamic_macro = true;
}

void dynamic_macro_record_end_user(int8_t direction) {
    is_recording_dynamic_macro = false;
}
#endif

static void render_status(void) {
    // QMK Logo and version information
    render_qmk_logo();
    oled_write_P(PSTR("\n"), false);

    // Host Keyboard Layer Status
    oled_write_P(PSTR("LAYER: "), false);
    switch (get_highest_layer(layer_state)) {
        case _QWERTY:
            oled_write_P(PSTR("qwerty\n"), false);
            break;
        case _NAV:
            oled_write_P(PSTR("navigation\n"), false);
            break;
        case _NUM:
            oled_write_P(PSTR("numpad\n"), false);
            break;
        case _FN:
            oled_write_P(PSTR("fn\n"), false);
            break;
        case _GAME:
            oled_write_P(PSTR("game\n"), false);
            break;
    }

    #ifdef DYNAMIC_MACRO_ENABLE
    oled_write_P(PSTR("REC: "), false);
    oled_write_P(is_recording_dynamic_macro ? PSTR("on\n") : PSTR("off\n"), false);
    #endif

    uint8_t mods = get_mods() | get_weak_mods();
    oled_write_P(PSTR("MODS: "), false);
    oled_write_P((mods & MOD_MASK_CTRL) ? PSTR("C ") : PSTR("  "), false);
    oled_write_P((mods & MOD_MASK_ALT) ? PSTR("A ") : PSTR("  "), false);
    oled_write_P((mods & MOD_MASK_GUI) ? PSTR("G ") : PSTR("  "), false);
    oled_write_P((mods & MOD_MASK_SHIFT) ? PSTR("S ") : PSTR("  "), false);
}

bool oled_task_user(void) {
    if (is_keyboard_master()) {
        render_status();
    } else {
        render_kyria_logo();
    }
    return false;
}
#endif
