OLED_ENABLE = no
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
RGBLIGHT_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
SPACE_CADET_ENABLE = yes
GRAVE_ESC_ENABLE = no
WPM_ENABLE = no
CONSOLE_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
UNICODE_ENABLE = no

SRC += features/casemodes.c
SRC += features/modprint.c
