ENCODER_ENABLE = yes
RGBLIGHT_ENABLE = yes
OLED_ENABLE = yes
SPACE_CADET_ENABLE = yes

WPM_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = no
STENO_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
KEY_LOCK_ENABLE = no
AUDIO_ENABLE = no
VELOCIKEY_ENABLE = no

MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
TERMINAL_ENABLE = no
CONSOLE_ENABLE = no
