#include QMK_KEYBOARD_H

enum custom_keycodes {
  RGB_SLD = EZ_SAFE_RANGE,
  ST_MACRO_0,
  ST_MACRO_1,
  ST_MACRO_2,
};

#define KC_MAC_UNDO LGUI(KC_Z)
#define KC_MAC_CUT LGUI(KC_X)
#define KC_MAC_COPY LGUI(KC_C)
#define KC_MAC_PASTE LGUI(KC_V)
#define KC_PC_UNDO LCTL(KC_Z)
#define KC_PC_CUT LCTL(KC_X)
#define KC_PC_COPY LCTL(KC_C)
#define KC_PC_PASTE LCTL(KC_V)
#define ES_LESS_MAC KC_GRAVE
#define ES_GRTR_MAC LSFT(KC_GRAVE)
#define ES_BSLS_MAC ALGR(KC_6)
#define NO_PIPE_ALT KC_GRAVE
#define NO_BSLS_ALT KC_EQUAL
#define LSA_T(kc) MT(MOD_LSFT | MOD_LALT, kc)
#define BP_NDSH_MAC ALGR(KC_8)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* .---------------------------------------------. .---------------------------------------------.
 * |ESCAPE |  1  |  2  |  3  |  4  |  5  |MEDIA_P| !AUDIO_M|  6  |  7  |  8  |  9  |  0  | MINUS |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * | GRAVE |  Q  |  W  |  E  |  R  |  T  |MEDIA_P| !MEDIA_N|  Y  |  U  |  I  |  O  |  P  |BSLASH |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |  TAB  |LCTL_|LALT_|LGUI_|LSFT_|  G  |-------! !-------!  H  |RSFT_|RGUI_|RALT_|RCTL_| QUOTE |
 * !-------+-----+-----+-----x-----x-----!AUDIO_V! !AUDIO_V!-----x-----x-----+-----+-----+-------!
 * | LSPO  |  Z  |  X  |  C  |  V  |  B  |       | !       |  N  |  M  |COMMA| DOT |RCTL_| RSPC  |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |LCTL(K|LSA_T|LCTRL|LALT |LGUI |                             !OSL(4|     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |  MEH  | HOME  | ! PGUP  | HYPR  |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !LT(2,KC!LT(3,KC|  END  | !PGDOWN |LT(3,KC!  LT   !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       | LGUI  | ! LALT  |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [0] = LAYOUT_ergodox_pretty(
    KC_ESCAPE,      KC_1,           KC_2,           KC_3,           KC_4,           KC_5,           KC_MEDIA_PLAY_PAUSE,                                KC_AUDIO_MUTE,       KC_6,        KC_7,          KC_8,           KC_9,           KC_0,                 KC_MINUS,
    KC_GRAVE,       KC_Q,           KC_W,           KC_E,           KC_R,           KC_T,           KC_MEDIA_PREV_TRACK,                                KC_MEDIA_NEXT_TRACK, KC_Y,        KC_U,          KC_I,           KC_O,           KC_P,                 KC_BSLASH,
    KC_TAB,         LCTL_T(KC_A),   LALT_T(KC_S),   LGUI_T(KC_D),   LSFT_T(KC_F),   KC_G,                                                                                    KC_H,        RSFT_T(KC_J),  RGUI_T(KC_K),   RALT_T(KC_L),   RCTL_T(KC_SCOLON),    KC_QUOTE,
    KC_LSPO,        KC_Z,           KC_X,           KC_C,           KC_V,           KC_B,           KC_AUDIO_VOL_DOWN,                                  KC_AUDIO_VOL_UP,     KC_N,        KC_M,          KC_COMMA,       KC_DOT,         RCTL_T(KC_SLASH),     KC_RSPC,
    LCTL(KC_LSHIFT),LSA_T(KC_NO),   KC_LCTRL,       KC_LALT,        KC_LGUI,                                                                                                              OSL(4),        KC_NO,          KC_NO,          KC_NO,                KC_NO,
                                                                                                    KC_MEH,         KC_HOME,        KC_PGUP,            KC_HYPR,
                                                                                                                    KC_END,         KC_PGDOWN,
                                                                                    LT(2,KC_BSPACE),LT(3,KC_DELETE),KC_LGUI,        KC_LALT,            LT(3,KC_ENTER),      LT(2,KC_SPACE)
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |ESCAPE |  1  |  2  |  3  |  4  |  5  |MEDIA_P| !AUDIO_M|  6  |  7  |  8  |  9  |  0  | MINUS |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * | GRAVE |  Q  |  W  |  E  |  R  |  T  |MEDIA_P| !MEDIA_N|  Y  |  U  |  I  |  O  |  P  |BSLASH |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |  TAB  |  A  |  S  |  D  |  F  |  G  |-------! !-------!  H  |  J  |  K  |  L  |SCOLO| QUOTE |
 * !-------+-----+-----+-----x-----x-----!AUDIO_V! !AUDIO_V!-----x-----x-----+-----+-----+-------!
 * | LSPO  |  Z  |  X  |  C  |  V  |  B  |       | !       |  N  |  M  |COMMA| DOT |RCTL_| RSPC  |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |LCTL(K|LSA_T|LCTRL|LALT |LGUI |                             !OSL(4|     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |  MEH  | HOME  | ! PGUP  | HYPR  |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !LT(2,KC!LT(3,KC|  END  | !PGDOWN |LT(3,KC!  LT   !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       | LGUI  | ! LALT  |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [1] = LAYOUT_ergodox_pretty(
    KC_ESCAPE,      KC_1,           KC_2,           KC_3,           KC_4,           KC_5,           KC_MEDIA_PLAY_PAUSE,                                KC_AUDIO_MUTE,       KC_6,        KC_7,          KC_8,           KC_9,           KC_0,                 KC_MINUS,
    KC_GRAVE,       KC_Q,           KC_W,           KC_E,           KC_R,           KC_T,           KC_MEDIA_PREV_TRACK,                                KC_MEDIA_NEXT_TRACK, KC_Y,        KC_U,          KC_I,           KC_O,           KC_P,                 KC_BSLASH,
    KC_TAB,         KC_A,           KC_S,           KC_D,           KC_F,           KC_G,                                                                                    KC_H,        KC_J,          KC_K,           KC_L,           KC_SCOLON,            KC_QUOTE,
    KC_LSPO,        KC_Z,           KC_X,           KC_C,           KC_V,           KC_B,           KC_AUDIO_VOL_DOWN,                                  KC_AUDIO_VOL_UP,     KC_N,        KC_M,          KC_COMMA,       KC_DOT,         RCTL_T(KC_SLASH),     KC_RSPC,
    LCTL(KC_LSHIFT),LSA_T(KC_NO),   KC_LCTRL,       KC_LALT,        KC_LGUI,                                                                                                              OSL(4),        KC_NO,          KC_NO,          KC_NO,                KC_NO,
                                                                                                    KC_MEH,         KC_HOME,        KC_PGUP,            KC_HYPR,
                                                                                                                    KC_END,         KC_PGDOWN,
                                                                                    LT(2,KC_BSPACE),LT(3,KC_DELETE),KC_LGUI,        KC_LALT,            LT(3,KC_ENTER),      LT(2,KC_SPACE)
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |LALT(LG| F1  | F2  | F3  | F4  | F5  |TRANSPA| !TRANSPA| F6  | F7  | F8  | F9  | F10 |  F11  |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |ESCAPE |CIRC | AT  |HASH |AMPR |PERC |TRANSPA| !TRANSPA| DLR |HOME | UP  | END |     |  F12  |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * | MO(5) |LCTRL|LALT |LGUI |LSFT |MINUS|-------! !-------!LALT(|LEFT |DOWN |RIGHT|ST_MA|CAPSLOC|
 * !-------+-----+-----+-----x-----x-----!TRANSPA! !TRANSPA!-----x-----x-----+-----+-----+-------!
 * |TRANSPA|     |     |     |     |UNDS |       | !       |LALT(|     |ST_MA|ST_MA|EXLM |TRANSPA|
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |DM_RE|DM_PL|                             !DM_PL|DM_RE|     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !BSPACE !DELETE |       | !       | ENTER ! SPACE !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [2] = LAYOUT_ergodox_pretty(
    LALT(LGUI(KC_ESCAPE)),KC_F1,    KC_F2,          KC_F3,          KC_F4,          KC_F5,          KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_F6,          KC_F7,          KC_F8,          KC_F9,          KC_F10,         KC_F11,
    KC_ESCAPE,      KC_CIRC,        KC_AT,          KC_HASH,        KC_AMPR,        KC_PERC,        KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_DLR,         KC_HOME,        KC_UP,          KC_END,         XXXXXXX,        KC_F12,
    MO(5),          KC_LCTRL,       KC_LALT,        KC_LGUI,        KC_LSFT,        KC_MINUS,                                                                       LALT(LSFT(KC_2)),KC_LEFT,       KC_DOWN,        KC_RIGHT,       ST_MACRO_2,     KC_CAPSLOCK,
    KC_TRANSPARENT, KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_UNDS,        KC_TRANSPARENT,                                 KC_TRANSPARENT, LALT(KC_3),     XXXXXXX,        ST_MACRO_0,     ST_MACRO_1,     KC_EXLM,        KC_TRANSPARENT,
    KC_NO,          KC_NO,          KC_NO,          DM_REC1,        DM_PLY1,                                                                                                        DM_PLY2,        DM_REC2,        KC_NO,          KC_NO,          KC_NO,
                                                                                                    KC_NO,          KC_NO,          KC_NO,          KC_NO,
                                                                                                                    KC_NO,          KC_NO,
                                                                                    KC_BSPACE,      KC_DELETE,      KC_NO,          KC_NO,          KC_ENTER,       KC_SPACE
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |     |TRANSPA| !TRANSPA|     |     |     |     |     |       |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |ESCAPE |     |     |LBRC |RBRC |     |TRANSPA| !TRANSPA|KP_AS| P7  | P8  | P9  |KP_SL|       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * | TG(5) |LCTRL|LALT |LGUI |LSFT |     |-------! !-------!KP_PL| P4  | P5  | P6  |KP_MI|       |
 * !-------+-----+-----+-----x-----x-----!TRANSPA! !TRANSPA!-----x-----x-----+-----+-----+-------!
 * |TRANSPA|     |     |LCBR |RCBR |     |       | !       | P0  | P1  | P2  | P3  |KP_EQ|TRANSPA|
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |     |     |                             ! DOT |COMMA|     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !BSPACE !DELETE |       | !       | ENTER ! SPACE !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [3] = LAYOUT_ergodox_pretty(
    KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,
    KC_ESCAPE,      KC_NO,          KC_NO,          KC_LBRC,        KC_RBRC,        KC_NO,          KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_KP_ASTERISK, KC_P7,          KC_P8,          KC_P9,          KC_KP_SLASH,    KC_NO,
    TG(5),          KC_LCTRL,       KC_LALT,        KC_LGUI,        KC_LSFT,        KC_NO,                                                                          KC_KP_PLUS,     KC_P4,          KC_P5,          KC_P6,          KC_KP_MINUS,    KC_NO,
    KC_TRANSPARENT, KC_NO,          KC_NO,          KC_LCBR,        KC_RCBR,        KC_NO,          KC_TRANSPARENT,                                 KC_TRANSPARENT, KC_P0,          KC_P1,          KC_P2,          KC_P3,          KC_KP_EQUAL,    KC_TRANSPARENT,
    KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,                                                                                                          KC_DOT,         KC_COMMA,       KC_NO,          KC_NO,          KC_NO,
                                                                                                    KC_NO,          KC_NO,          KC_NO,          KC_NO,
                                                                                                                    KC_NO,          KC_NO,
                                                                                    KC_BSPACE,      KC_DELETE,      KC_NO,          KC_NO,          KC_ENTER,       KC_SPACE
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |ESCAPE |     |     |     |     |     |       | !       |     | F7  | F8  | F9  | F10 |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |LCTRL|LALT |LGUI |LSFT |     |-------! !-------!     | F4  | F5  | F6  | F11 |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     | F1  | F2  | F3  | F12 |       |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |     |     |                             !     |     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !       !       |       | !       |       !       !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [4] = LAYOUT_ergodox_pretty(
    KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,                                    KC_NO,        KC_NO,        KC_NO,          KC_NO,         KC_NO,         KC_NO,        KC_NO,
    KC_ESCAPE,      KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,                                    KC_NO,        KC_NO,        KC_F7,          KC_F8,         KC_F9,         KC_F10,       KC_NO,
    KC_NO,          KC_LCTRL,       KC_LALT,        KC_LGUI,        KC_LSFT,        KC_NO,                                                                  KC_NO,        KC_F4,          KC_F5,         KC_F6,         KC_F11,       KC_NO,
    KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,                                    KC_NO,        KC_NO,        KC_F1,          KC_F2,         KC_F3,         KC_F12,       KC_NO,
    KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,                                                                                                KC_NO,          KC_NO,         KC_NO,         KC_NO,        KC_NO,
                                                                                                    KC_NO,          KC_NO,     KC_NO,         KC_NO,
                                                                                                                    KC_NO,     KC_NO,
                                                                                    KC_NO,          KC_NO,          KC_NO,     KC_NO,         KC_NO,        KC_NO
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |TOGGL|RGB_TOG| !RGB_MOD|RGB_S|     |     |     |     |LGUI(LS|
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |       |     |     |MS_UP|     |     |RGB_VAD| !RGB_VAI|     |     |MS_WH|     |     |LGUI(LS|
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * | TG(5) |     |MS_LE|MS_DO|MS_RI|     |-------! !-------!     |MS_WH|MS_WH|MS_WH|     |LCTL(LG|
 * !-------+-----+-----+-----x-----x-----!RGB_HUD! !RGB_HUI!-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     |MS_AC|MS_AC|MS_AC|     |LCTL(LG|
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |DF(1)|DF(0)|                             !     |     |     |     |LGUI(L|
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |WEBUSB_|       | !       | RESET |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !MS_BTN1!MS_BTN2|       | !       | BRID  ! BRIU  !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |MS_BTN3| !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [5] = LAYOUT_ergodox_pretty(
    KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          TOGGLE_LAYER_COLOR,RGB_TOG,                                     RGB_MOD,        RGB_SLD,        KC_NO,          KC_NO,          KC_NO,          KC_NO,          LGUI(LSFT(KC_3)),
    KC_NO,          KC_NO,          KC_NO,          KC_MS_UP,       KC_NO,          KC_NO,          RGB_VAD,                                        RGB_VAI,        KC_NO,          KC_NO,          KC_MS_WH_UP,    KC_NO,          KC_NO,          LGUI(LSFT(KC_4)),
    TG(5),          KC_NO,          KC_MS_LEFT,     KC_MS_DOWN,     KC_MS_RIGHT,    KC_NO,                                                                          KC_NO,          KC_MS_WH_LEFT,  KC_MS_WH_DOWN,  KC_MS_WH_RIGHT, KC_NO,          LCTL(LGUI(LSFT(KC_3))),
    KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          KC_NO,          RGB_HUD,                                        RGB_HUI,        KC_NO,          KC_MS_ACCEL0,   KC_MS_ACCEL1,   KC_MS_ACCEL2,   KC_NO,          LCTL(LGUI(LSFT(KC_4))),
    KC_NO,          KC_NO,          KC_NO,          DF(1),          DF(0),                                                                                                          KC_NO,          KC_NO,          KC_NO,          KC_NO,          LGUI(LSFT(KC_5)),
                                                                                                    WEBUSB_PAIR,    KC_NO,          KC_NO,          RESET,
                                                                                                                    KC_NO,          KC_NO,
                                                                                    KC_MS_BTN1,     KC_MS_BTN2,     KC_MS_BTN3,     KC_NO,          KC_BRID,        KC_BRIU
  ),
};

bool get_tapping_force_hold(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LT(2,KC_BSPACE):
        case LT(3,KC_DELETE):
        case LT(3,KC_ENTER):
        case LT(2,KC_SPACE):
            return true;
        default:
            return false;
    }
}

bool disable_layer_color = 0;

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case ST_MACRO_0:
    if (record->event.pressed) {
      SEND_STRING(SS_LSFT(SS_TAP(X_COMMA)) SS_DELAY(100) SS_TAP(X_EQUAL));

    }
    break;
    case ST_MACRO_1:
    if (record->event.pressed) {
      SEND_STRING(SS_LSFT(SS_TAP(X_DOT)) SS_DELAY(100) SS_TAP(X_EQUAL));

    }
    break;
    case ST_MACRO_2:
    if (record->event.pressed) {
      SEND_STRING(SS_TAP(X_MINUS) SS_DELAY(100) SS_LSFT(SS_TAP(X_DOT)));

    }
    break;
    case RGB_SLD:
      if (record->event.pressed) {
        rgblight_mode(1);
      }
      return false;
    case TOGGLE_LAYER_COLOR:
      if (record->event.pressed) {
        disable_layer_color ^= 1;
      }
      return false;
  }
  return true;
}

#ifdef DYNAMIC_MACRO_ENABLE
bool is_dynamic_recording = false;
bool is_dynamic_recording_led_on = false;
uint16_t dynamic_loop_timer;

void dynamic_macro_record_start_user(void) {
    is_dynamic_recording = true;
    is_dynamic_recording_led_on = true;
    dynamic_loop_timer = timer_read();
}

void dynamic_macro_record_end_user(int8_t direction) {
    is_dynamic_recording = false;
    is_dynamic_recording_led_on = false;
    layer_state_set_user(layer_state);
}
#endif

void matrix_scan_user(void) {
    #ifdef DYNAMIC_MACRO_ENABLE
    if (is_dynamic_recording) {
        if (timer_elapsed(dynamic_loop_timer) > 300) {
            if (is_dynamic_recording_led_on) {
                ergodox_right_led_1_on();
                ergodox_right_led_2_on();
                ergodox_right_led_3_on();
            } else {
                ergodox_right_led_1_off();
                ergodox_right_led_2_off();
                ergodox_right_led_3_off();
            }
            is_dynamic_recording_led_on = !is_dynamic_recording_led_on;
            dynamic_loop_timer = timer_read();
        }
    }
    #endif
}

rgblight_config_t rgblight_config;

uint32_t layer_state_set_user(uint32_t state) {
    uint8_t layer = biton32(state);

    ergodox_board_led_off();
    ergodox_right_led_1_off();
    ergodox_right_led_2_off();
    ergodox_right_led_3_off();

    switch (layer) {
      case 2:
        ergodox_right_led_1_on();
        break;
      case 3:
        ergodox_right_led_2_on();
        break;
      case 5:
        ergodox_right_led_3_on();
        break;
      case 4:
        ergodox_right_led_1_on();
        ergodox_right_led_2_on();
        ergodox_right_led_3_on();
        break;
      default:
        break;
    }

    switch (layer) {
      case 2:
        if(!disable_layer_color) {
          rgblight_enable_noeeprom();
          rgblight_mode_noeeprom(1);
          rgblight_sethsv_noeeprom(0,231,213);
        }
        break;
      case 3:
        if(!disable_layer_color) {
          rgblight_enable_noeeprom();
          rgblight_mode_noeeprom(1);
          rgblight_sethsv_noeeprom(77,233,213);
        }
        break;
      case 5:
        if(!disable_layer_color) {
          rgblight_enable_noeeprom();
          rgblight_mode_noeeprom(1);
          rgblight_sethsv_noeeprom(163,230,207);
        }
        break;
      default:
        if(!disable_layer_color) {
          rgblight_config.raw = eeconfig_read_rgblight();
          if(rgblight_config.enable == true) {
            rgblight_enable();
            rgblight_mode(rgblight_config.mode);
            rgblight_sethsv(rgblight_config.hue, rgblight_config.sat, rgblight_config.val);
          }
          else {
            rgblight_disable();
          }
        }
        break;
    }

    return state;
};

void keyboard_post_init_user(void) {
    layer_state_set_user(layer_state);
}
