#include QMK_KEYBOARD_H

enum layers {
    _QWERTY_HRM = 0,
    _QWERTY,
    _STENO,
    _NAV,
    _NUM,
    _FN,
    _EXTRA,
};

enum custom_keycodes {
  RGB_SLD = EZ_SAFE_RANGE,
  ARROW,
  LOWER,
  GREATER,
  HRM,
  PLON,
  PLOF,
  DELAY1,
  DELAY2,
  DELAY3,
};

#define CTL_A LCTL_T(KC_A)
#define ALT_S LALT_T(KC_S)
#define GUI_D LGUI_T(KC_D)
#define SFT_F LSFT_T(KC_F)
#define SFT_J RSFT_T(KC_J)
#define GUI_K RGUI_T(KC_K)
#define ALT_L RALT_T(KC_L)
#define CTLSCL LCTL_T(KC_SCLN)
#define CTLSLS LCTL_T(KC_SLSH)

#define SYM_BSPC LT(_NAV, KC_BSPC)
#define SYM_SPC LT(_NAV, KC_SPC)
#define NUM_DEL LT(_NUM, KC_DELETE)
#define NUM_ENT LT(_NUM, KC_ENT)

#define FN OSL(_FN)
#define TGEXT TG(_EXTRA)
#define TTEXT TT(_EXTRA)

#define EURO LALT(LSFT(KC_2))
#define POUND LALT(KC_3)

#define UNDO LGUI(KC_Z)
#define CUT LGUI(KC_X)
#define COPY LGUI(KC_C)
#define PASTE LGUI(KC_V)
#define FORCEQ LALT(LGUI(KC_ESCAPE))

#define PRTSCR4 LGUI(LSFT(KC_3))
#define PRTSCR5 LGUI(LSFT(KC_4))
#define PRTSCR1 LCTL(LGUI(LSFT(KC_3)))
#define PRTSCR2 LCTL(LGUI(LSFT(KC_4)))
#define PRTSCR3 LGUI(LSFT(KC_5))

#define TLAYCOL TOGGLE_LAYER_COLOR
#define ORYX WEBUSB_PAIR

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* .---------------------------------------------. .---------------------------------------------.
 * |  ESC  |  1  |  2  |  3  |  4  |  5  | MPLY  | ! MUTE  |  6  |  7  |  8  |  9  |  0  | MINS  |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |  TAB  |  Q  |  W  |  E  |  R  |  T  | MPRV  | ! MNXT  |  Y  |  U  |  I  |  O  |  P  | BSLS  |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |  GRV  |CTL_A|ALT_S|GUI_D|SFT_F|  G  |-------! !-------!  H  |SFT_J|GUI_K|ALT_L|CTLSC| QUOT  |
 * !-------+-----+-----+-----x-----x-----! VOLD  ! ! VOLU  !-----x-----x-----+-----+-----+-------!
 * | LSPO  |  Z  |  X  |  C  |  V  |  B  |       | !       |  N  |  M  |COMM | DOT |SLSH | RSPC  |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |LCTRL|LALT |LGUI |                             !TTEXT|     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |  MEH  | HOME  | ! PGUP  | HYPR  |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !SYM_BSP!NUM_DEL|  END  | ! PGDN  |NUM_ENT!SYM_SPC!
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       | LGUI  | ! LALT  |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [_QWERTY_HRM] = LAYOUT_ergodox_pretty(
     KC_ESC,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5, KC_MPLY,                                     KC_MUTE,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0, KC_MINS,
     KC_TAB,    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T, KC_MPRV,                                     KC_MNXT,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P, KC_BSLS,
     KC_GRV,   CTL_A,   ALT_S,   GUI_D,   SFT_F,    KC_G,                                                          KC_H,   SFT_J,   GUI_K,   ALT_L,  CTLSCL, KC_QUOT,
    KC_LSPO,    KC_Z,    KC_X,    KC_C,    KC_V,    KC_B, KC_VOLD,                                     KC_VOLU,    KC_N,    KC_M, KC_COMM,  KC_DOT, KC_SLSH, KC_RSPC,
    XXXXXXX, XXXXXXX,KC_LCTRL, KC_LALT, KC_LGUI,                                                                           TTEXT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                    KC_MEH, KC_HOME, KC_PGUP, KC_HYPR,
                                                                             KC_END, KC_PGDN,
                                                         SYM_BSPC, NUM_DEL, KC_LGUI, KC_LALT, NUM_ENT, SYM_SPC
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |  ESC  |  1  |  2  |  3  |  4  |  5  | MPLY  | ! MUTE  |  6  |  7  |  8  |  9  |  0  | MINS  |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |  TAB  |  Q  |  W  |  E  |  R  |  T  | MPRV  | ! MNXT  |  Y  |  U  |  I  |  O  |  P  | BSLS  |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |  GRV  |  A  |  S  |  D  |  F  |  G  |-------! !-------!  H  |  J  |  K  |  L  |SCLN | QUOT  |
 * !-------+-----+-----+-----x-----x-----! VOLD  ! ! VOLU  !-----x-----x-----+-----+-----+-------!
 * | LSPO  |  Z  |  X  |  C  |  V  |  B  |       | !       |  N  |  M  |COMM | DOT |SLSH | RSPC  |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |LCTRL|LALT |LGUI |                             !TTEXT|     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |  MEH  | HOME  | ! PGUP  | HYPR  |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !SYM_BSP!NUM_DEL|  END  | ! PGDN  |NUM_ENT!SYM_SPC!
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       | LGUI  | ! LALT  |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [_QWERTY] = LAYOUT_ergodox_pretty(
     KC_ESC,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5, KC_MPLY,                                     KC_MUTE,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0, KC_MINS,
     KC_TAB,    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T, KC_MPRV,                                     KC_MNXT,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P, KC_BSLS,
     KC_GRV,    KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                                                          KC_H,    KC_J,    KC_K,    KC_L, KC_SCLN, KC_QUOT,
    KC_LSPO,    KC_Z,    KC_X,    KC_C,    KC_V,    KC_B, KC_VOLD,                                     KC_VOLU,    KC_N,    KC_M, KC_COMM,  KC_DOT, KC_SLSH, KC_RSPC,
    XXXXXXX, XXXXXXX,KC_LCTRL, KC_LALT, KC_LGUI,                                                                           TTEXT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                    KC_MEH, KC_HOME, KC_PGUP, KC_HYPR,
                                                                             KC_END, KC_PGDN,
                                                         SYM_BSPC, NUM_DEL, KC_LGUI, KC_LALT, NUM_ENT, SYM_SPC
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |       |  1  |  2  |  3  |  4  |  5  |       | !       |  6  |  7  |  8  |  9  |  0  |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |  Q  |  W  |  E  |  R  |  T  |-------! !-------!  Y  |  U  |  I  |  O  |  P  | LBRC  |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |  A  |  S  |  D  |  F  |  G  |       | !       |  H  |  J  |  K  |  L  |SCLN | QUOT  |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |     |PLOF |                             !     |     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !   C   !   V   |       | !       |   N   !   M   !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [_STENO] = LAYOUT_ergodox_pretty(
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5, XXXXXXX,                                     XXXXXXX,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0, XXXXXXX,
    XXXXXXX,    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                                                          KC_Y,    KC_U,    KC_I,    KC_O,    KC_P, KC_LBRC,
    XXXXXXX,    KC_A,    KC_S,    KC_D,    KC_F,    KC_G, XXXXXXX,                                     XXXXXXX,    KC_H,    KC_J,    KC_K,    KC_L, KC_SCLN, KC_QUOT,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,    PLOF,                                                                         XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                            XXXXXXX, XXXXXXX,
                                                             KC_C,    KC_V, XXXXXXX, XXXXXXX,    KC_N,    KC_M
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |FORCEQ | F1  | F2  | F3  | F4  | F5  |       | !       | F6  | F7  | F8  | F9  | F10 |  F11  |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |  TAB  |CIRC | AT  |HASH |AMPR |PERC |       | !       |     |HOME | UP  | END |     |  F12  |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |  ESC  |LCTL |LALT |LGUI |LSFT |MINS |-------! !-------!     |LEFT |DOWN |RGHT |ARROW| CAPS  |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * | LSPO  |UNDO | CUT |COPY |PASTE|UNDS |       | !       |     |     |LOWER|GREAT|EXLM | RSPC  |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |DM_RE|DM_PL|                             !DM_PL|DM_RE|     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       ! BSPC  !  DEL  |       | !       |  ENT  !  SPC  !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [_NAV] = LAYOUT_ergodox_pretty(
     FORCEQ,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5, XXXXXXX,                                     XXXXXXX,   KC_F6,   KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11,
     KC_TAB, KC_CIRC,   KC_AT, KC_HASH, KC_AMPR, KC_PERC, XXXXXXX,                                     XXXXXXX, XXXXXXX, KC_HOME,   KC_UP,  KC_END, XXXXXXX,  KC_F12,
     KC_ESC, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_MINS,                                                       XXXXXXX, KC_LEFT, KC_DOWN, KC_RGHT,   ARROW, KC_CAPS,
    KC_LSPO,    UNDO,     CUT,    COPY,   PASTE, KC_UNDS, XXXXXXX,                                     XXXXXXX, XXXXXXX, XXXXXXX,   LOWER, GREATER, KC_EXLM, KC_RSPC,
    XXXXXXX, XXXXXXX, XXXXXXX, DM_REC1, DM_PLY1,                                                                         DM_PLY2, DM_REC2, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                            XXXXXXX, XXXXXXX,
                                                          KC_BSPC,  KC_DEL, XXXXXXX, XXXXXXX,  KC_ENT,  KC_SPC
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |  TAB  |     |     |LBRC |RBRC | DLR |       | !       |ASTR |  7  |  8  |  9  |SLSH |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |  ESC  |LCTL |LALT |LGUI |LSFT |EURO |-------! !-------!PLUS |  4  |  5  |  6  |MINS |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * | LSPO  |     |     |LCBR |RCBR |POUND|       | !       |  0  |  1  |  2  |  3  | EQL | RSPC  |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |     |OSL(5|                             ! DOT |COMM |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       ! BSPC  !  DEL  |       | !       |  ENT  !  SPC  !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [_NUM] = LAYOUT_ergodox_pretty(
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
     KC_TAB, XXXXXXX, XXXXXXX, KC_LBRC, KC_RBRC,  KC_DLR, XXXXXXX,                                     XXXXXXX, KC_ASTR,    KC_7,    KC_8,    KC_9, KC_SLSH, XXXXXXX,
     KC_ESC, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT,    EURO,                                                       KC_PLUS,    KC_4,    KC_5,    KC_6, KC_MINS, XXXXXXX,
    KC_LSPO, XXXXXXX, XXXXXXX, KC_LCBR, KC_RCBR,   POUND, XXXXXXX,                                     XXXXXXX,    KC_0,    KC_1,    KC_2,    KC_3,  KC_EQL, KC_RSPC,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  OSL(5),                                                                          KC_DOT, KC_COMM, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                            XXXXXXX, XXXXXXX,
                                                          KC_BSPC,  KC_DEL, XXXXXXX, XXXXXXX,  KC_ENT,  KC_SPC
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |     |       | !       |     |     |     |     |     |       |
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     | F7  | F8  | F9  | F10 |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |  ESC  |LCTL |LALT |LGUI |LSFT |     |-------! !-------!     | F4  | F5  | F6  | F11 |       |
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |       |     |     |     |     |     |       | !       |     | F1  | F2  | F3  | F12 |       |
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     |     |     |                             !     |     |     |     |      |
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       !       !       |       | !       |       !       !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       |       | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [_FN] = LAYOUT_ergodox_pretty(
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                                     XXXXXXX, XXXXXXX,   KC_F7,   KC_F8,   KC_F9,  KC_F10, XXXXXXX,
     KC_ESC, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, XXXXXXX,                                                       XXXXXXX,   KC_F4,   KC_F5,   KC_F6,  KC_F11, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                                     XXXXXXX, XXXXXXX,   KC_F1,   KC_F2,   KC_F3,  KC_F12, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                                                                         XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                            XXXXXXX, XXXXXXX,
                                                          XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
  ),
/* .---------------------------------------------. .---------------------------------------------.
 * |       |     |     |     |     |TLAYC|RGB_TOG| !RGB_MOD|RGB_S|     |     |     |     |PRTSCR4|
 * !-------+-----+-----+-----+-----+-------------! !-------+-----+-----+-----+-----+-----+-------!
 * |DELAY1 |     |     |MS_U |     |     |RGB_VAD| !RGB_VAI|     |     |WH_U |     |     |PRTSCR5|
 * !-------+-----+-----+-----x-----x-----!       ! !       !-----x-----x-----+-----+-----+-------!
 * |DELAY2 |     |MS_L |MS_D |MS_R |     |-------! !-------!     |WH_L |WH_D |WH_R |     |PRTSCR1|
 * !-------+-----+-----+-----x-----x-----!RGB_HUD! !RGB_HUI!-----x-----x-----+-----+-----+-------!
 * |DELAY3 |     |     |     |     |     |       | !       |     |ACL0 |ACL1 |ACL2 |     |PRTSCR2|
 * '-------+-----+-----+-----+-----+-------------' '-------------+-----+-----+-----+-----+-------'
 *  |      |     |     | HRM |PLON |                             !TG(6)|RESET|ORYX |     |PRTSCR|
 *  '------------------------------'                             '------------------------------'
 *                               .---------------. .---------------.
 *                               |       |       | !       |       |
 *                       .-------+-------+-------! !-------+-------+-------.
 *                       ! BTN1  ! BTN2  |       | !       | BRID  ! BRIU  !
 *                       !       !       !-------! !-------!       !       !
 *                       |       |       | BTN3  | !       |       |       |
 *                       '-----------------------' '-----------------------'
 *                                                  generated by [keymapviz] */
  [_EXTRA] = LAYOUT_ergodox_pretty(
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, TLAYCOL, RGB_TOG,                                     RGB_MOD, RGB_SLD, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, PRTSCR4,
     DELAY1, XXXXXXX, XXXXXXX, KC_MS_U, XXXXXXX, XXXXXXX, RGB_VAD,                                     RGB_VAI, XXXXXXX, XXXXXXX, KC_WH_U, XXXXXXX, XXXXXXX, PRTSCR5,
     DELAY2, XXXXXXX, KC_MS_L, KC_MS_D, KC_MS_R, XXXXXXX,                                                       XXXXXXX, KC_WH_L, KC_WH_D, KC_WH_R, XXXXXXX, PRTSCR1,
     DELAY3, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, RGB_HUD,                                     RGB_HUI, XXXXXXX, KC_ACL0, KC_ACL1, KC_ACL2, XXXXXXX, PRTSCR2,
    XXXXXXX, XXXXXXX, XXXXXXX,     HRM,    PLON,                                                                           TG(6),   RESET,    ORYX, XXXXXXX, PRTSCR3,
                                                                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
                                                                            XXXXXXX, XXXXXXX,
                                                          KC_BTN1, KC_BTN2, KC_BTN3, XXXXXXX, KC_BRID, KC_BRIU
  ),
};

bool get_tapping_force_hold(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case SYM_BSPC:
        case SYM_SPC:
        case NUM_DEL:
        case NUM_ENT:
        case ALT_L:
            return true;
        default:
            return false;
    }
}

bool is_hrm_enabled = true;
bool disable_layer_color = 0;

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case LOWER:
    if (record->event.pressed) {
      SEND_STRING(SS_LSFT(SS_TAP(X_COMMA)) SS_DELAY(100) SS_TAP(X_EQUAL));
    }
    break;
    case GREATER:
    if (record->event.pressed) {
      SEND_STRING(SS_LSFT(SS_TAP(X_DOT)) SS_DELAY(100) SS_TAP(X_EQUAL));
    }
    break;
    case ARROW:
    if (record->event.pressed) {
      SEND_STRING(SS_TAP(X_MINUS) SS_DELAY(100) SS_LSFT(SS_TAP(X_DOT)));
    }
    break;
    case HRM:
    if (record->event.pressed) {
      layer_clear();
      is_hrm_enabled = !is_hrm_enabled;
      is_hrm_enabled ? default_layer_set(1UL << _QWERTY_HRM) : default_layer_set(1UL << _QWERTY);
    }
    return false;
    case PLON:
    if (record->event.pressed) {
      layer_clear();
      default_layer_set(1UL << _STENO);

      register_code(KC_E);
      register_code(KC_R);
      register_code(KC_F);
      register_code(KC_V);
      register_code(KC_I);
      register_code(KC_K);
      unregister_code(KC_E);
      unregister_code(KC_R);
      unregister_code(KC_F);
      unregister_code(KC_V);
      unregister_code(KC_I);
      unregister_code(KC_K);
    }
    return false;
    case PLOF:
    if (record->event.pressed) {
      layer_clear();
      is_hrm_enabled ? default_layer_set(1UL << _QWERTY_HRM) : default_layer_set(1UL << _QWERTY);

      register_code(KC_E);
      register_code(KC_R);
      register_code(KC_F);
      register_code(KC_V);
      register_code(KC_T);
      register_code(KC_U);
      unregister_code(KC_E);
      unregister_code(KC_R);
      unregister_code(KC_F);
      unregister_code(KC_V);
      unregister_code(KC_T);
      unregister_code(KC_U);
    }
    return false;
    case DELAY1:
    if (record->event.pressed) {
      _delay_ms(250);
    }
    break;
    case DELAY2:
    if (record->event.pressed) {
      _delay_ms(500);
    }
    break;
    case DELAY3:
    if (record->event.pressed) {
      _delay_ms(1000);
    }
    break;
    case RGB_SLD:
      if (record->event.pressed) {
        rgblight_mode(1);
      }
      return false;
    case TOGGLE_LAYER_COLOR:
      if (record->event.pressed) {
        disable_layer_color ^= 1;
      }
      return false;
  }
  return true;
}

#ifdef DYNAMIC_MACRO_ENABLE
bool is_dynamic_recording = false;
bool is_dynamic_recording_led_on = false;
uint16_t dynamic_loop_timer;

void dynamic_macro_record_start_user(void) {
    is_dynamic_recording = true;
    is_dynamic_recording_led_on = true;
    dynamic_loop_timer = timer_read();
}

void dynamic_macro_record_end_user(int8_t direction) {
    is_dynamic_recording = false;
    is_dynamic_recording_led_on = false;
    layer_state_set_user(layer_state);
}
#endif

void matrix_scan_user(void) {
    #ifdef DYNAMIC_MACRO_ENABLE
    if (is_dynamic_recording) {
        if (timer_elapsed(dynamic_loop_timer) > 300) {
            if (is_dynamic_recording_led_on) {
                ergodox_right_led_1_on();
                ergodox_right_led_2_on();
                ergodox_right_led_3_on();
            } else {
                ergodox_right_led_1_off();
                ergodox_right_led_2_off();
                ergodox_right_led_3_off();
            }
            is_dynamic_recording_led_on = !is_dynamic_recording_led_on;
            dynamic_loop_timer = timer_read();
        }
    }
    #endif
}

rgblight_config_t rgblight_config;

uint32_t layer_state_set_user(uint32_t state) {
    uint8_t layer = biton32(state);

    ergodox_board_led_off();
    ergodox_right_led_1_off();
    ergodox_right_led_2_off();
    ergodox_right_led_3_off();

    switch (layer) {
      case _NAV:
        ergodox_right_led_1_on();
        break;
      case _NUM:
        ergodox_right_led_2_on();
        break;
      case _EXTRA:
        ergodox_right_led_3_on();
        break;
      case _FN:
        ergodox_right_led_1_on();
        ergodox_right_led_2_on();
        ergodox_right_led_3_on();
        break;
      default:
        break;
    }

    switch (layer) {
      case _NAV:
        if(!disable_layer_color) {
          rgblight_enable_noeeprom();
          rgblight_mode_noeeprom(1);
          rgblight_sethsv_noeeprom(0,231,213);
        }
        break;
      case _NUM:
        if(!disable_layer_color) {
          rgblight_enable_noeeprom();
          rgblight_mode_noeeprom(1);
          rgblight_sethsv_noeeprom(77,233,213);
        }
        break;
      case _EXTRA:
        if(!disable_layer_color) {
          rgblight_enable_noeeprom();
          rgblight_mode_noeeprom(1);
          rgblight_sethsv_noeeprom(163,230,207);
        }
        break;
      default:
        if(!disable_layer_color) {
          rgblight_config.raw = eeconfig_read_rgblight();
          if(rgblight_config.enable == true) {
            rgblight_enable();
            rgblight_mode(rgblight_config.mode);
            rgblight_sethsv(rgblight_config.hue, rgblight_config.sat, rgblight_config.val);
          }
          else {
            rgblight_disable();
          }
        }
        break;
    }

    return state;
};

void keyboard_post_init_user(void) {
    layer_state_set_user(layer_state);
}
